name: Tests

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11-dev"]
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip nox
      - name: Run tests
        run: |
          python -m nox -s tests
      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          fail_ci_if_error: True

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.0
